stages:
  - lint
  - test
  - package

services:
  - name: postgres:16
    alias: postgres

variables: # https://docs.gitlab.com/ci/services/postgres/#use-postgresql-with-the-docker-executor
  PROTECTED_BRANCH: master
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD  # Expected by Psql
  POSTGRES_PASS: $POSTGRES_PASSWORD  # Expected by Django settings
  DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

before_script:
  - apt update
  - apt-get --no-install-recommends install -y
      gcc
      git
      libpq-dev
      libxmlsec1-dev
      libxmlsec1-openssl
      libxml2-dev
      libxslt-dev
      libssl-dev
      pkg-config
      postgresql-client
      python3-pip
  - pip install --upgrade pip
  - python -m venv /tmp/venv
  - source /tmp/venv/bin/activate
  - pip install
      diff-cover
      twine
      wheel
      xmlsec==1.3.14 
  - pip install -r requirements.txt
  - find . -name 'requirements.*.txt'
      -exec pip install --pre 
      --index-url ${CI_API_V4_URL}/groups/${CI_PROJECT_NAMESPACE_ID}/-/packages/pypi/simple/
      -r {} \;

lint:
  stage: lint
  image: python:3.10-slim-bullseye
  script:
    - black --check .
    - flake8 --extend-ignore E501 .
  rules:
    - if: $CI_COMMIT_BRANCH
      when: always

test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.9', '3.10', '3.11', '3.12']
  image: python:${PYTHON_VERSION}-slim-bullseye
  script:
    - coverage run --parallel --source=core_federated_search_app --omit=*settings.py -p runtests.py
    - coverage combine || true
    - coverage xml
    - diff-cover coverage.xml --compare-branch=origin/$PROTECTED_BRANCH --fail-under=100
  rules:
    - if: $CI_COMMIT_BRANCH
      when: on_success

package:
  stage: package
  image: python:3.10-slim-bullseye
  script:
    - rm -rf dist *.egg-info
    - sed -i "s/version=\"\([^\"]*\)\"/version=\"\1.dev$(date +"%Y%m%d%H%M")\"/" setup.py
    - python3 setup.py sdist bdist_wheel --verbose
    - export TWINE_PASSWORD=${CI_JOB_TOKEN}
    - export TWINE_USERNAME=gitlab-ci-token
    - twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: '$CI_COMMIT_BRANCH != $PROTECTED_BRANCH'
      when: on_success
