""" Migration to allow federated search on public instances.

Generated by Django 4.2 on 2024-04-15.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_federated_search_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="access_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
